### ISSUE TITLE
COBie Attribute v2.4 versioning

### ISSUE THREAD

**Issue by vdubya** [OpenAIM/OpenRFA-Website#36]
Current [COBie Attribute](http://dev.openrfa.org/cobie) and [COBie Mapping](http://dev.openrfa.org/mapping/cobie) lists are specific to COBie v2.4. Need **versioning** and version labeling strategy as COBie v3 is not far away. My hunch is separate tables would be best rather than versioning per attribute in one table.

- [ ] At a minimum in the near term, the [COBie Attribute](http://dev.openrfa.org/cobie) and [COBie Mapping](http://dev.openrfa.org/mapping/cobie) pages need to update titles/labels to include “v2.4”

**Comment by jmerlan** [comment]
Are there major changes in v3? Can you send me a spreadsheet similar to the v2.4 so that we can come up with a strategy for this? 

My inclination would be to try to use the same content type, but use something like tags to help specify if an attribute is v2.4, v3, or both (if that is even a possibility). If an attribute can never be both v2.4 and v3 then it does make sense for them to be completely separate entities.

**Comment by jmerlan** [comment]
Implemented in v1.0.

Each COBie Attribute now has a multi-select field to assign it to multiple COBie versions.
